# for local development
version: '3.7'
services:
  frontend:
    build:
      context: .
      #target: 'develop-stage'
      #image: realworldvue3_frontend:latest
    ports:
    - '8080:8080'
    volumes:
    - './Real-World_Vue-3/:/app/'
    - './Real-World_Vue-3/node_modules/:/app/node_modules/'
      #command:  npm run vue ui
    command: npm run serve
